### ISSUE TITLE
media-sound/helvum-9999: libawaita & gui-libs/gtk version dependencies update

### ISSUE THREAD

**Issue by CaptainBloodz** [tezeta/tezeta-overlay#1]
media-sound/helvum-9999 now requires
>=gui-libs/libadwaita-1.4.0 as in:
`From https://gitlab.freedesktop.org/pipewire/helvum
   903df21..b983ade  HEAD       -> refs/git-r3/HEAD
git symbolic-ref refs/git-r3/media-sound/helvum/0/__main__ refs/git-r3/HEAD
 * Checking out https://gitlab.freedesktop.org/pipewire/helvum.git to /var/no-tmpfs/portage/media-sound/helvum-9999/work/helvum-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://gitlab.freedesktop.org/pipewire/helvum.git
   updating from commit:     903df21ba36c05db92a784ac47e00cda73fcdb57
   to commit:                b983ade736f612bece2b7d5874bd09510c78a701
 Cargo.toml                |  2 +-
 meson.build               |  2 +-
 src/style.css             | 17 +++++++++++++++++
 src/ui/graph/zoomentry.rs |  1 +
 src/ui/graph/zoomentry.ui | 31 +++++++++++++++++++++----------
 src/ui/window.ui          | 65 ++++++++++++++++++++++++++++++++++++-----------------------------
 6 files changed, 77 insertions(+), 41 deletions(-)
>>> Source unpacked in /var/no-tmpfs/portage/media-sound/helvum-9999/work
>>> Preparing source in /var/no-tmpfs/portage/media-sound/helvum-9999/work/helvum-9999 ...
>>> Source prepared.
>>> Configuring source in /var/no-tmpfs/portage/media-sound/helvum-9999/work/helvum-9999 ...
meson setup --libdir lib64 --localstatedir /var/lib --prefix /usr --sysconfdir /etc --wrap-mode nodownload --build.pkg-config-path /usr/share/pkgconfig --pkg-config-path /usr/share/pkgconfig --native-file /var/no-tmpfs/portage/media-sound/helvum-9999/temp/meson.x86_64-pc-linux-gnu.amd64.ini -Db_pch=false -Dwerror=false --buildtype plain /var/no-tmpfs/portage/media-sound/helvum-9999/work/helvum-9999 /var/no-tmpfs/portage/media-sound/helvum-9999/work/helvum-9999-build
The Meson build system
Version: 1.2.1
Source dir: /var/no-tmpfs/portage/media-sound/helvum-9999/work/helvum-9999
Build dir: /var/no-tmpfs/portage/media-sound/helvum-9999/work/helvum-9999-build
Build type: native build
Project name: helvum
Project version: 0.5.1
Rust compiler for the host machine: rustc -C linker=x86_64-pc-linux-gnu-gcc (rustc 1.73.0-nightly)
Rust linker for the host machine: rustc -C linker=x86_64-pc-linux-gnu-gcc ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/x86_64-pc-linux-gnu-pkg-config (1.8.1)
Run-time dependency glib-2.0 found: YES 2.76.4
Run-time dependency gtk4 found: YES 4.10.5
Dependency libadwaita-1 found: NO found 1.3.4 but need: '>= 1.4'`

`Dependency resolution took 13.18 s.
[ebuild   R   ~] media-sound/helvum-9999 
[ebuild     U ~] gui-libs/libadwaita-1.4.0 [1.3.4]
[ebuild  N     ]  dev-libs/appstream-0.15.6  USE="-apt -doc -introspection -qt5 -test" 
[ebuild     U ~]  gui-libs/gtk-4.12.2 [4.10.5]
[nomerge       ] dev-libs/appstream-0.15.6  USE="-apt -doc -introspection -qt5 -test" 
[ebuild  N     ]  dev-libs/snowball-stemmer-2.2.0  USE="-static-libs -test" 
`
So >=gui-libs/gtk-4.12.2 keywording is enough to remain as stable as possible.

**Comment by tezeta** [comment]
Thank you, this should be fixed with d2addba.
