### ISSUE TITLE
pystopwatch-2020.10.01: missing dependency: "gi"

### ISSUE THREAD

**Issue by F3llFr0mTh3Sky** [tezeta/tezeta-overlay#2]
See the screenshot :
![image](https://github.com/tezeta/tezeta-overlay/assets/142761866/271b097b-3f9d-47a2-8628-505f0c6e98af)

**Comment by tezeta** [comment]
This is likely due to pygobject lacking the PYTHON_TARGET use flag "python3_10". The ebuild now expands out the required target in the ebuild with 4d3f019/693c3c4, which should require the correct USE flag for pygobject when emerging. Let me know if it's still failing.

**Comment by F3llFr0mTh3Sky** [comment]
Thanks a lot for the fix, but couldn't you add python_3_11 as supported  target?
I would like to minimize the amount of dependencies to rebuild for each new targets:
![image](https://github.com/tezeta/tezeta-overlay/assets/142761866/0ff473ab-2baa-436c-98e4-b5e4d0fd6c80)
Now it is like a lot.
