### ISSUE TITLE
xfce4-docklike-plugin wrong source

### ISSUE THREAD

**Issue by Outtay** [tezeta/tezeta-overlay#4]
I've made a local overlay to fix this for myself, but after running into a minor problem with dependencies I thought it might be useful to have a better and more "official" version not only for me, but for others as well.

Googling "xfce4-docklike-plugin" unfortunately returns https://github.com/nsz32/docklike-plugin which hasn't had any updates since years and issues are also ignored. However, the official and still active repository is here: https://gitlab.xfce.org/panel-plugins/xfce4-docklike-plugin 
It even has more features that are documented on the [official xfce4 page](https://docs.xfce.org/panel-plugins/xfce4-docklike-plugin/start), which is why I'd advocate for updating the ebuild to use this repository instead (and I hope it would work without many changes)

**Comment by tezeta** [comment]
Updated the source and added a depend for libxfce4windowing. Thanks!
